METHOD_GET = 'GET'
METHOD_HEAD = 'HEAD'

MAX_LINE = 64*1024
MAX_HEADERS = 100

HTTP_STATUS_CODE_OK = 200
HTTP_STATUS_CODE_FORBIDDEN = 403
HTTP_STATUS_CODE_NOT_FOUND = 404
HTTP_STATUS_CODE_METHOD_NOT_ALLOWED = 405

HTTP_EOF = '\r\n'
